[package]
name = "aph"
version = "0.2.0"
description = "A library for acyclic phase-type (APH) distributions."
authors = ["Maximilian Köhl <mail@koehlma.de>"]
edition = "2021"
repository = "https://github.com/koehlma/aph-rs"
license = "MIT"

[dependencies]
rug = "1.15.0"
thiserror = "1.0.30"

[package.metadata.docs.rs]
rustdoc-args = [
    "--html-in-header", "./docs/katex-header.html",
]